options:
  health-scale: 20
  attribute:
    #tick
    time:
      attribute-update: 10
      attribute-clear: 1200
    ignores:
      - '//'
    line-condition:
      #记得转义
      format: '.*\/(?<requirement>.*)'
      separator: ','
stats:
  title: '&8&d{name} &8的属性统计:'
  attribute-format: '&7{name}: &c{value}'